happy/urls.py
from django.urls import include, path
from . import views

app_name = 'happy'

urlpatterns = [
    path('', views.home, name='home'),
    path('watch/', views.watch, name='watch'),
    path('games/', views.games, name='games'),
    path('music/', views.music, name='music'),
    path('search/', views.searchKeyword, name='searchKeyword'),
    path('detail/<str:detail_id>/', views.detail, name='detail'),

    path('netflix/', views.netflix, name='netflix'),
    path('commentNetflix/', views.commentNetflix, name='commentNetflix'),
    path('deleteNetflix/<int:delete_id>', views.deleteNetflix, name='deleteNetflix'),

    path('anime/', views.anime, name='anime'),
    path('deleteAnime/<int:delete_id>', views.deleteAnime, name='deleteAnime'),
    path('commentAnime/', views.commentAnime, name='commentAnime'),

    path('kdrama/', views.kdrama, name='kdrama'),
    path('deleteKdrama/<int:delete_id>', views.deleteKdrama, name='deleteKdrama'),
    path('commentKdrama/', views.commentKdrama, name='commentKdrama'),

    path('romantic/', views.romantic, name='romantic'),
    path('deleteRomantic/<int:delete_id>', views.deleteRomantic, name='deleteRomantic'),
    path('commentRomantic/', views.commentRomantic, name='commentRomantic'),

    path('tiktok/', views.tiktok, name='tiktok'),
    path('deleteTiktok/<int:delete_id>', views.deleteTiktok, name='deleteTiktok'),
    path('commentTiktok/', views.commentTiktok, name='commentTiktok'),

    path('podcast/', views.podcast, name='podcast'),
    path('deletePodcast/<int:delete_id>', views.deletePodcast, name='deletePodcast'),
    path('commentPodcast/', views.commentPodcast, name='commentPodcast'),

    path('kpop/', views.kpop, name='kpop'),
    path('deleteKpop/<int:delete_id>', views.deleteKpop, name='deleteKpop'),
    path('commentKpop/', views.commentKpop, name='commentKpop'),

    path('games1/', views.games1, name='games1'),
    path('deleteGames1/<int:delete_id>', views.deleteGames1, name='deleteGames1'),
    path('commentGames1/', views.commentGames1, name='commentGames1'),

    path('games2/', views.games2, name='games2'),
    path('deleteGames2/<int:delete_id>', views.deleteGames2, name='deleteGames2'),
    path('commentGames2/', views.commentGames2, name='commentGames2'),

    # dilanjutkan ...
]

home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.view_logout, name = 'logout')
]

staces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('happy/', include(('happy.urls', 'happy'), namespace='happy')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('foryou/', include(('foryou.urls', 'foryou'), namespace='foryou')),
    path('', include('main.urls')),
]

home/models.py
from django.db import models

# Create your models here.

happy/forms.py
from django import forms 

class CommentForm(forms.Form):
    content = forms.CharField(
        label = "Write Comment",
        widget = forms.Textarea(
            attrs = {
                'class':'form-control w-100',
                'max_length : 100'
                'cols' : '30',
                'rows' : '10',
                'id' : 'content',
                'placeholder' : 'Write Comment',
            }
        )
    )

class SearchForm(forms.Form):
    input = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'search',
                'placeholder' : 'Search Keyword',
            }
        )
    )

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

happy/views.py
from django.shortcuts import render, redirect 
from .models import Article, Comment, CommentKdrama, CommentPodcast, CommentAnime, CommentKpop, CommentRomantic, CommentGames1, CommentGames2, CommentTiktok
from . import forms
from django.http import JsonResponse
from django.contrib.auth.models import User

def home(request):
    return render(request, 'home.html')

def watch(request):
    return render(request, 'watch.html')

def music(request):
    return render(request, 'music.html')

def games(request):
    return render(request, 'games.html')

# =====================================================================================================

def searchKeyword(request):
    word = request.GET.get('search_keyword')
    object_list = Article.objects.filter(keyword__icontains=word)
    return render(request, 'searchView.html', {'list':object_list}) 

def detail(request, detail_id):
    blog_detail = Article.objects.get(name = detail_id)
    if blog_detail.name == 'netflix':
        return redirect('/happy/netflix')
    elif blog_detail.name == 'kdrama':
        return redirect('/happy/kdrama')
    elif blog_detail.name == 'romantic':
        return redirect('/happy/romantic')
    elif blog_detail.name == 'anime':
        return redirect('/happy/anime')
    elif blog_detail.name == 'tiktok':
        return redirect('/happy/tiktok')
    elif blog_detail.name == 'podcast':
        return redirect('/happy/podcast')
    elif blog_detail.name == 'kpop':
        return redirect('/happy/kpop')
    elif blog_detail.name == 'games1':
        return redirect('/happy/games1')
    elif blog_detail.name == 'games2':
        return redirect('/happy/games2')
    else:
        return redirect('')

# =====================================================================================================

def netflix(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = Comment()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = Comment.objects.all()
        return render(request, 'netflix.html', {'form':comment_form, 'data':data})      
    
def commentNetflix(request):
    data = {
        'data':[i.get_dict() for i in Comment.objects.all()],
    }
    return JsonResponse(data=data)

def deleteNetflix(request, delete_id):
    try:
        deleted_subject = Comment.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False})  

# =====================================================================================================

def anime(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentAnime()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentAnime.objects.all()
        return render(request, 'anime.html', {'form':comment_form, 'data':data})   

def commentAnime(request):
    data = {
        'data':[i.get_dict() for i in CommentAnime.objects.all()],
    }
    return JsonResponse(data=data)   

def deleteAnime(request, delete_id):
    try:
        deleted_subject = CommentAnime.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False}) 

# =====================================================================================================

def kdrama(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentKdrama()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentKdrama.objects.all()
        return render(request, 'kdrama.html', {'form':comment_form, 'data':data})     

def commentKdrama(request):
    data = {
        'data':[i.get_dict() for i in CommentKdrama.objects.all()],
    }
    return JsonResponse(data=data)

def deleteKdrama(request, delete_id):
    try:
        deleted_subject = CommentKdrama.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False}) 

# =====================================================================================================

def podcast(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentPodcast()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentPodcast.objects.all()
        return render(request, 'podcast.html', {'form':comment_form, 'data':data})     

def commentPodcast(request):
    data = {
        'data':[i.get_dict() for i in CommentPodcast.objects.all()],
    }
    return JsonResponse(data=data)

def deletePodcast(request, delete_id):
    try:
        deleted_subject = CommentPodcast.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False}) 

# =====================================================================================================

def kpop(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentKpop()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentKpop.objects.all()
        return render(request, 'kpop.html', {'form':comment_form, 'data':data})     

def commentKpop(request):
    data = {
        'data':[i.get_dict() for i in CommentKpop.objects.all()],
    }
    return JsonResponse(data=data)

def deleteKpop(request, delete_id):
    try:
        deleted_subject = CommentKpop.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False}) 

# =====================================================================================================

def games1(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentGames1()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentGames1.objects.all()
        return render(request, 'games1.html', {'form':comment_form, 'data':data})   

def commentGames1(request):
    data = {
        'data':[i.get_dict() for i in CommentGames1.objects.all()],
    }
    return JsonResponse(data=data)  

def deleteGames1(request, delete_id):
    try:
        deleted_subject = CommentGames1.objects.get(pk = delete_id)
        deleted_subject.delete()
        return JsonResponse({'success': True})
    except:
        return JsonResponse({'success': False})

# =====================================================================================================

def games2(request):
    comments = {}
    if request.method ==  'POST':
        if request.is_ajax():
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                data = comment_form.cleaned_data
                comment_input = CommentGames2()
                comment_input.author = request.user.username
                comment_input.content = data['content']
                comment_input.save()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        comment_form = forms.CommentForm()
        data = CommentGames2.objects.all()

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import RegisForm
from django.utils.safestring import mark_safe

# Create your views here.

def index(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

        else :
            messages.error(request,'Username or password not correct')

    return render(request, 'index.html')

def register(request):
    if request.method == "POST":
        form = RegisForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulations, your account has been successfully created! Please Kindly Login on the Login Button')
        else :
            messages.error(request, mark_safe("ERROR: Something went wrong. User Registration failed<br/>Requirements:<br/>1. Username required 150 characters or fewer. Letters, digits, and @/./+/-/_ only.<br/>2. Enter the same password as before<br/>3. Your password must contain at least 8 character<br/>4. Your password can't be a commonly used password, entirely numeric, and similiarlu to username"))

    else :
        form = RegisForm()
    return render(request, 'register.html', {'form' : form})

def view_logout(request):
    logout(request)
    return redirect('/')

happy/templates/baseHappy.html
<!doctype html>
{% extends "navbarHappy.html" %}

{% block head %}
<html class="no-js" lang="zxx">

{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Abril+Fatface"/>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Happy Space </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">

<!-- CSS here -->
    <link rel="stylesheet" href="{% static 'happy/cssHappy/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/slick.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/styleHappy.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/responsive.css' %}">  
</head>

<body data-bubble-img="{% static 'happy/imgHappy/tk1/circle.png' %}">

<!-- Preloader Start -->
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'happy/imgHappy/tk1/happy.png' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap">
                            <h2>Happy Space!</h2>
                            <br></br>
                            <p>This is a relaxing space to clear your mind after went through the day.<br>
                            There will be various categories of entertainment that you can do at home.<br>
                            The categories are music, movies, and games. Each category will be presented<br>
                            with articles containing recommendations along with a brief description.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

{% block content %}
{% endblock %}
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="{% url 'happy:home' %}" class="d-flex">
                                        <p>What to do?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:watch' %}" class="d-flex">
                                        <p>What to watch?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:music' %}" class="d-flex">
                                        <p>Music</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:games' %}" class="d-flex">
                                        <p>Games</p>
                                    </a>
                                </li>
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget search_widget">
                            <a class="d-flex">
                                <p>What is your interest?</p>
                            </a>
                            <form action="{% url 'happy:searchKeyword' %}" method="GET">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input id="search_keyword" name="search_keyword" type="text" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btns" type="button"><i class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search</button>
                            </form>
                            <br>
                            <a class="d-flex">
                                <p>Try to search:</p>
                            </a>
                            <div style="display:flex; flex-wrap: wrap; justify-content: space-around;" class="flex-container">
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item">netflix </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> korea </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> drama </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> games </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> series </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> anime </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> wibu </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> kpop </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> tiktok </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> social distancing </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> show </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> boyband </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> fantasy </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> romance </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> viral </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> 2020 </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> dance </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> podcast </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> quarantine </div>
                                <div id="keyword-flex" style = "font-family: 'Josefin Sans'; font-size: 15px; color: black; border-style: outset; margin: 6px;" class="flex-item"> watching </div>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- JS here -->
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script>
        $(document).ready(function(){
            $("input").focus(function(){
                $(this).css("background-color", "#ffe8d6");
            });
            $("input").blur(function(){
                $(this).css("background-color", "white");
            });
            $(".flex-item").mouseover(function(){
                $(this).css("border-style", "inset");
            });
            $(".flex-item").mouseout(function(){
                $(this).css("border-style", "outset");
            });
        });
        </script>
        <!-- Comment section -->
        <script type="text/javascript"> DJANGO_STATIC_URL = '{{ STATIC_URL }}'; </script>
        <script src="{% static 'happy/jsHappy/comment.js' %}"></script>
        <script src="{% static 'happy/jsHappy/commentKdrama.js' %}"></script>
        <script src="{% static 'happy/jsHappy/anime.js' %}"></script>
        <script src="{% static 'happy/jsHappy/romantic.js' %}"></script>
        <script src="{% static 'happy/jsHappy/tiktok.js' %}"></script>
        <script src="{% static 'happy/jsHappy/kpop.js' %}"></script>
        <script src="{% static 'happy/jsHappy/podcast.js' %}"></script>
        <script src="{% static 'happy/jsHappy/games1.js' %}"></script>
        <script src="{% static 'happy/jsHappy/games2.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
        <script src="{% static 'happy/jsHappy/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/bootstrap.min.js' %}"></script>
		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'happy/jsHappy/slick.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.slicknav.min.js' %}"></script>
		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'happy/jsHappy/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.sticky.js' %}"></script>
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'happy/jsHappy/plugins.js' %}"></script>
        <script src="{% static 'happy/jsHappy/main.js' %}"></script>
</body>
</html>

{% endblock %}

happy/templates/watch.html
<!DOCTYPE html>
{% extends "baseHappy.html" %}

    {% block content %}

    {% load static %}
    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
        <a class="d-inline-block">
            <h2 id="h2-blog">What to watch in quarantine?</h2>
        </a>
        <br></br>
        <br></br>
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{% static 'happy/imgHappy/tk1/netflix.png' %}" alt="">
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'happy:netflix' %}">
                                    <h2 id="h2-blog">Top 10 Netflix series to watch in 2020</h2>
                                </a>
                            </div>
                        </article>

                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{% static 'happy/imgHappy/tk1/drakor.png' %}" alt="">
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'happy:kdrama' %}">
                                    <h2 id="h2-blog">5 Korean Dramas That'll Keep You Entertained While You're Social Distancing</h2>
                                </a>
                            </div>
                        </article>

                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{% static 'happy/imgHappy/tk1/romance.png' %}" alt="">
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'happy:romantic' %}">
                                    <h2 id="h2-blog">The 10 Best Romantic Movies of All Time</h2>
                                </a>
                            </div>
                        </article>

                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{% static 'happy/imgHappy/tk1/sao.jpg' %}" alt="">
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'happy:anime' %}">
                                    <h2 id="h2-blog">Which anime series are a must-watch?</h2>
                                </a>
                            </div>
                        </article>
                    </div>
                </div>
{% endblock %}