foryou/urls.py
from django.urls import include, path
from .views import index, read, send, save, history, show, asave, like

urlpatterns = [
    path('', index, name='index'),
    path('read/', read, name='read'),
    path('send/', send, name='send'),
    path('send/save', save, name='save'),
    path('history/', history, name='history'),
    path('show/', show, name='show'),
    path('asave/', asave, name='asave'),
    path('like/', like, name='like')
]

home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.view_logout, name = 'logout')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

staces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('happy/', include(('happy.urls', 'happy'), namespace='happy')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('foryou/', include(('foryou.urls', 'foryou'), namespace='foryou')),
    path('', include('main.urls')),
]

foryou/models.py
from django.db import models
from django.contrib.auth.models import User

class Pesan(models.Model):
    name = models.CharField(max_length=50, default='Anonymous')
    awal = models.CharField(max_length=1, default='')
    message = models.TextField(max_length=200, default='')
    sender = models.CharField(max_length=150, default='')
    like = models.DecimalField(max_digits=10,decimal_places=0)
    date = models.DateField(null = True)

main/models.py
from django.db import models

# Create your models here.

foryou/forms.py
from django import forms
from .models import Pesan

class Input_Form(forms.ModelForm):
    class Meta:
        model = Pesan
        fields = ['name', 'message']
    input_name = {
        'type' : 'text',
        'placeholder' : 'leave it blank to be Anonymous',
        'class' : 'in_n'
    }
    input_message = {
        'type' : 'text',
        'placeholder' : 'write something',
        'class' : 'in_m'
    }
    name = forms.CharField(label='Name/Initial', required=False, widget=forms.TextInput(attrs=input_name))
    message = forms.CharField(label='Messages', max_length=200, required=True, widget=forms.Textarea(attrs=input_message))

foryou/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import Max, Min
from .forms import Input_Form
from .models import Pesan
import random, datetime, json

lst = ["Alligator","Anteater","Armadillo","Auroch","Axolotl","Badger","Bat","Beaver","Buffalo","Camel","Capybara","Chameleon","Cheetah","Chinchilla","Chipmunk","Chupacabra","Cormorant","Coyote","Crow","Dingo","Dinosaur","Dolphin","Duck","Elephant","Ferret","Fox","Frog","Giraffe","Gopher","Grizzly","Hedgehog","Hippo","Hyena","Ibex","Ifrit","Iguana","Jackal","Kangaroo","Koala","Kraken","Lemur","Leopard","Liger","Llama","Manatee","Mink","Monkey","Moose","Narwhal","Orangutan","Otter","Panda","Penguin","Platypus","Pumpkin","Python","Quagga","Rabbit","Raccoon","Rhino","Sheep","Shrew","Skunk","Squirrel","Tiger","Turtle","Walrus","Wolf","Wolverine","Wombat"]
ada = False

def index(request):
    return render(request, 'main/index.html')

def read(request):
    message = Pesan.objects.all()
    response = {'messages' : message, 'success' : False}
    return render(request, 'main/read.html', response)

def send(request):
    response = {'form' : Input_Form}
    return render(request, 'main/send.html', response)

def save(request):
    form = Input_Form(request.POST)
    if (request.method == 'POST' and form.is_valid()):
        nama = form.cleaned_data['name']
        pesan = form.cleaned_data['message']
        user = ''
        if (request.user.is_authenticated):
            user = request.user.username
        if (nama == ''):
            hewan = random.choice(lst)
            lst.remove(hewan)
            new = Pesan(name="Anonymous " + hewan, message=pesan, awal=hewan[0], like=0, sender=user, date=datetime.date.today())
        else:
            new = Pesan(name=nama, message=pesan, awal=nama[0].upper(), like=0, sender=user, date=datetime.date.today())
        new.save()
        response = {'messages' : Pesan.objects.all(), 'success' : True}
        global ada
        ada = True
        return render(request, 'main/read.html', response)
    return HttpResponseRedirect('/foryou/send')

def history(request):
    response = {'messages' : Pesan.objects.filter(sender=request.user.username).order_by('-date')}
    return render(request, 'main/history.html', response)

def show(request):
    count = Pesan.objects.count()
    choose = random.randint(1, count)
    
    global ada    
    if ada:
        ada = False
        choose = Pesan.objects.aggregate(Max('pk'))['pk__max']

    obj = Pesan.objects.get(id=choose)
    ser_obj = serializers.serialize('json', [obj, ])
    data = json.loads(ser_obj)
    return JsonResponse(data, safe=False)

def asave(request):
    nama = request.GET['n']
    pesan = request.GET['m']
    user = ''
    if (request.user.is_authenticated):
        user = request.user.username
    if (nama == ''):
        hewan = random.choice(lst)
        lst.remove(hewan)
        new = Pesan(name="Anonymous " + hewan, message=pesan, awal=hewan[0], like=0, sender=user, date=datetime.date.today())
    else:
        new = Pesan(name=nama, message=pesan, awal=nama[0].upper(), like=0, sender=user, date=datetime.date.today())
    new.save()

    ind = Pesan.objects.aggregate(Max('pk'))['pk__max']
    obj = Pesan.objects.get(id=ind)
    ser_obj = serializers.serialize('json', [obj, ])
    data = json.loads(ser_obj)
    return JsonResponse(data, safe=False)

def like(request):
    nama = request.GET['n']
    pesan = request.GET['m']

    obj = Pesan.objects.get(name=nama, message=pesan)
    obj.like = obj.like + 1
    obj.save()

    ser_obj = serializers.serialize('json', [obj, ])
    data = json.loads(ser_obj)
    return JsonResponse(data, safe=False)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

foryou/templates/main/history.html
{% extends 'main/navbar.html' %}
{% load static %}

{% block meta %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/foryou.css' %}">
<title>History</title>

{% endblock meta %}

{% block content %}

<div class="container" id="header">
    <p id="headLeft3">
      Your Messages
    </p>
</div>

<div class="container" id="boxHistory">
    <p id=userHistory>
      User : {{ user.username }}
    </p>
    {% if messages %}

        {% for message in messages %}
          <hr id="batasHistory" width="50%">
          {% if message.sender == user.username %}
            <p id="listPesan">
              <p id=pesan>
                {{message.message}}
              </p>
              <p id="detail">
                <i class="fa fa-heart" id="like"> </i> {{message.like}} <br> 
                <i class="fa fa-send" id="like"> </i> {{message.date}}
              </p>
            </p>
            {% endif %}
          {% endfor %}
          <hr id="batasHistory" width="50%">

    {% else %}
        <p id="noPesan">
          no messages yet :(
        </p>
    {% endif %}
    <p id="thanks" class="back">
      <a href="{% url 'foryou:read' %}">
        back
      </a> 
    </p>
</div>

{% endblock content %}

foryou/templates/main/index.html
{% extends 'main/navbar.html' %}
{% load static %}

{% block meta %}

<link rel="stylesheet" href="{% static 'css/foryou.css' %}">
<title>For You!</title>

{% endblock meta %}

{% block content %}

<div class="container" id="header">    
  <div class="row">

    <div class="col" id="headLeft"> 
      <p id="headLeft1">
        For You
      </p>
      <p id="headLeft2">
        Imagine staying at home because of pandemic for several months. You must be feeling lonely, right?
        Dont worry, in this features you can found lots of friends by communicate each other!
        Even you can give motivational messages for the others who have the same condition as you!
        What are you waiting for? Lets give happiness to each other :) 
      </p>
    </div>

    <div class="col-md-4" id="headRight">
      <img src="{% static 'img/letter.png' %}" id="imgRight">
    </div>

  </div>
</div>

<div class="container" id="colMain">
  <div class="row">

    <div class="col">
      <a href="{% url 'foryou:read' %}">
        <button type="button" class="btn btn-danger">
          <p class="homeText">
            Click here
          </p>
        </button>
      </a>

      <p class="homeText" id="textBlue">
        to read your messages!!
      </p>
    </div>

    <div class="col-1">
      <p class="homeText" id="textBlue">
        or
      </p>
    </div>

    <div class="col" id="colRight">
      <a href="{% url 'foryou:send' %}">
        <button type="button" class="btn btn-danger">
          <p class="homeText">
            Click here
          </p>
        </button>
      </a>

      <p class="homeText" id="textBlue">
        to spread happiness around you!!
      </p>
      
    </div>
  </div>
  {% if not user.is_authenticated %}
  <p id="tips">
    *login for special features ^^
  </p>
  {% endif %}
</div>

{% endblock content %}

foryou/templates/main/navbar.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c">

	
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<link rel="icon" href="{% static 'img/staces-logo.png' %}">
	<title>For You</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
	{% block meta %}
	{% endblock meta %}

</head>
<body>


<div id="page-wrap">
	<!-- ==========================================================================================================
													   HERO
		 ========================================================================================================== -->

	<div id="">
		<nav class="navbar navbar-expand-lg navbar-light main-navbar-nav1">
			<a class="navbar-brand" href="">STACES</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		  
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav nav-items-center ml-auto mr-auto">
				<li class="nav-item">
					  <a class="nav-link" href="{% url 'home:index' %}">Home</a>
				</li>
				<li class="nav-item">
					  <a class="nav-link" href="{% url 'todo:index' %}">TO DO</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'happy:home' %}">Happy</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'learning:index' %}">Learning</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'foryou:index' %}">For You<span class="sr-only">(current)</span></a>
				</li>
				{% if user.is_authenticated %}
					<a href="#">
						<div class="social-icons-header">
							<a href="/logout/">
								<button type="button" class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log Out</button>
							  </a>
						</div>
					</a>
					<span style="margin-top: 5px; margin-left: 10px; height: 40px; width: 40px; font-family: 'Josefin Sans'; font-size: 25px; text-align: center; background-color: #102542; border-radius: 50%; color: #fff;">{{ user.username.0 }}</span>
					{% else %}
					<a href="/#log-in">
						<div class="social-icons-header">
							<button class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log In</button>
						</div>
					</a>
					{% endif %}
			  </ul>
			</div>
		  </nav>
		
    </div> 
	
	{% block content %}
	{% endblock content %}

	<!-- ==========================================================================================================
                                               FOOTER
    ========================================================================================================== -->

	<footer class="footer-outer">
		<div class="container footer-inner">

			<div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
				<div>
					<nav class="footer-nav">
						<ul>
							<h1 id="h1-footer"> STACES </h1>
							<p>By using our website, we hope that we helped you. Stay safe, stay healthy, and stay clean!<br>
							If there is any problem, please let we know.</p>
						</ul>
						<ul>
							<div class="social-icons-footer">
								<a target="_blank" href="https://instagram.com/stacesapp/"><i class="fab fa-instagram"></i></a>
								<a target="_blank" href="mailto: stacesapp@gmail.com"><i class="fa fa-envelope"></i></i></a>
							</div>
						</ul>
						<ul>
							<p class="copyright" id="p-copyright">Copyright © 2020. All Rights Reserved</p>
						</ul>
					</nav>
				</div>
			</div>
			<span></span>
			<p class="copyright"></p>
		</div>
	</footer>

</div> <!-- main page wrapper -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

foryou/templates/main/read.html
{% extends 'main/navbar.html' %}
{% load static %}

{% block meta %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/foryou.css' %}">
<title>Read Messages</title>

{% endblock meta %}

{% block content %}
<div class="container" id="header">
    <p id="headLeft3">
      Read Messages
    </p>
</div>

<div class="slideshow-container">
    <div class="mySlides">
        <p id="nama">
            <span id="ava"></span>
        </p>
        <hr>
        <p id="pesan"></p>
        <div style="position: absolute;">
            <i class="fa fa-heart-o"></i>
            <i class="fa fa-heart" style="display: none;"></i>
            <div class="myCount"></div>
        </div>
        <a href="#" id="plus">
            <button type="button" class="btn btn-danger" id="addButton">
                +
            </button>
        </a>
    
    </div>

    <a class="prev">&#10094;</a>
    <a class="next">&#10095;</a>
    
</div>

<div id="boxThanks">
    {% if success %}
    <p id="thanks">
        thank you, your message has already sent :) 
    </p>
    {% endif %}

    {% if user.is_authenticated %}
        <p id="thanks">            
            see your <a href="{% url 'foryou:history' %}"> messages </a>
        </p>
    {% endif %}
</div>

<div id="read2" style="display: none;">
    
    <hr id="batas">
    <p id="form2">
        Name / Initial
    </p>
    <input name="name" placeholder="leave it blank to be Anonymous" class="in_n">
    <br>
    <br>
    <p id="form2">
        Messages
    </p>
    <p id="limit">
        (0/200)
    </p>
    <textarea placeholder="write something" name="message" required maxlength="200" rows="4" cols="65" class="in_m2"></textarea>
    <br>
    <button class="btn btn-danger" id="buttonSend2">
        <p class="sendButton">
            SEND
        </p>
    </button>

</div>
<p id="dummy">{{user.username}}</p>

<script src="{% static 'js/foryou.js' %}"></script>

{% endblock content %}

foryou/templates/main/send.html
{% extends 'main/navbar.html' %}
{% load static %}

{% block meta %}

<link rel="stylesheet" href="{% static 'css/foryou.css' %}">
<title>Send Messages</title>

{% endblock meta %}

{% block content %}

<div class="container" id="header">
    <p id="headLeft3">
      Send Messages
    </p>
</div>

<div class="container" id="boxForm">
  <form action="save" method="POST">
    <h6 id="textSend">
      Name / Initial
    </h6>

    <p id="textHolder">
      {% csrf_token %}
      {{form.name}}
    </p>

    <p id="textSend" class="messagesMain">
      Messages
    </p>
    
    <p id="limit2">
      (0/200)
    </p>

    <p id="textHolder">
      {% csrf_token %}
      {{form.message}}
    </p>

    <p>
      <a href="{% url 'foryou:read' %}">
        <button type="button" class="btn btn-danger">
          <p class="sendButton">
            BACK
          </p>
        </button>
      </a>
      
      <button type="submit" class="btn btn-danger" id="buttonSend">
        <p class="sendButton" id="sendReal">
          SEND
        </p>
      </button>
            
    </p>

  </form>
</div>

<script src="{% static 'js/foryou.js' %}"></script>

{% endblock content %}