home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.view_logout, name = 'logout')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

staces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('happy/', include(('happy.urls', 'happy'), namespace='happy')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('foryou/', include(('foryou.urls', 'foryou'), namespace='foryou')),
    path('', include('main.urls')),
]

todo/urls.py
from django.urls import include, path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('addTask/',  views.addTask, name='addTask'),
    path('getPersonalTask/', views.getPersonalTask, name = 'getPersonalTask'),
    path('getGroupTask/', views.getGroupTask, name = 'getGroupTask'),
    path('getAllTask/', views.getAllTask, name = 'getAllTask'),
    path('deleteTask/<int:task_id>', views.deleteTask, name='deleteTask'),
]

main/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User

task_categories = (
    ("Personal Task", "Personal Task"),
    ("Group Task", "Group Task"),
)

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="task", null=True)
    title = models.CharField('Task Title', max_length = 100, null = True)
    description = models.TextField('Task Description', null = True)
    category = models.CharField('Task Category', choices = task_categories, default = "Personal Task", max_length=20, null = True)
    date = models.DateField('Date', null = True)
    time = models.TimeField('time', null = True)

todo/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "category",
        ]

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

todo/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import TaskForm
from .models import Task

def index(request):
    if request.user.is_authenticated:
        all_task = request.user.task.order_by('date', 'time', 'title')
    else :
        all_task = []
    return render(request, 'main/todo.html', {'allTask' : all_task})

def addTask(request):
    taskform = TaskForm()
    if request.method == "POST":
        taskForm = TaskForm(request.POST)
        if taskForm.is_valid():
            task = Task(
                title = request.POST['title'],
                description = request.POST['description'],
                category = request.POST['category'],
                date = request.POST['date'],
                time = request.POST['time'],
            )
            task.save()
            request.user.task.add(task)
            return JsonResponse({"result" : "POSTED"})

    return render(request, 'main/add-task.html', {'taskform' : taskform})

def getPersonalTask(request):
    all_task = request.user.task.filter(category = "Personal Task").order_by('date', 'time', 'title').values()
    return JsonResponse({"result" : list(all_task)})

def getGroupTask(request):
    all_task = request.user.task.filter(category = "Group Task").order_by('date', 'time', 'title').values()
    return JsonResponse({"result" : list(all_task)})

def getAllTask(request):
    all_task = request.user.task.order_by('date', 'time', 'title').values()
    return JsonResponse({"result" : list(all_task)})

def deleteTask(request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    return JsonResponse({"result" : "Task has been deleted"})

todo/templates/main/add-task.html
{% extends 'main/navfoot-todo.html' %}
{% load static %}

{% block meta %}
<title>TO DO - Add Task Page</title>
{% endblock meta %}

{% block title %}
<div id="fh5co-hero-wrapper-study-add-task">
{% endblock %}

{% block desc %}
<div class="animated fadeIn wow container todo-desc">
    <div class="todo-section-title">Create a New Task</div>
</div>
{% endblock %}

{% block content %}
<div class="animated fadeIn wow container content">
    <form method="POST" class="task-form">
        {% csrf_token %}

        <div class="field">
            <label for="title" class="label-field">Task Title</label>
            {{taskform.title}}
        </div>

        <div class="field">
            <label for="description" class="label-field">Task Description</label>
            {{taskform.description}}
        </div>

        <div class="field">
            <label for="category" class="label-field">Task Category</label>
            {{taskform.category}}
        </div>

        <div class="field">
            <label for="date" class="label-field">Deadline - Date</label>
            <input type="date" name="date" required>
        </div>

        <div class="field">
            <label for="time" class="label-field">Deadline - Time</label>
            <input type="time" name="time" required>
        </div>

        <button type="button" class="btn submit-button p-2">Create Task</button>

    </form>
</div>
{% endblock %}

todo/templates/main/navfoot-todo.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/todo.css' %}">
	<link rel="icon" href="{% static 'img/staces-logo.png' %}">
	
	{% block meta %}
	{% endblock %}
</head>
<body>


<div id="page-wrap">
	<!-- ==========================================================================================================
													   HERO
		 ========================================================================================================== -->
    {% block title %}
	<div id="fh5co-hero-wrapper-study">
    {% endblock %}
	<nav class="navbar navbar-expand-lg navbar-light main-navbar-nav1">
		<a class="navbar-brand" href="">STACES</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav nav-items-center ml-auto mr-auto">
			<li class="nav-item">
				  <a class="nav-link" href="{% url 'home:index' %}">Home</a>
			</li>
			<li class="nav-item active">
				  <a class="nav-link" href="{% url 'todo:index' %}">TO DO<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'happy:home' %}">Happy</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'learning:index' %}">Learning</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'foryou:index' %}">For You</a>
			</li>
			{% if user.is_authenticated %}
				<a href="#">
					<div class="social-icons-header">
						<a href="/logout/">
							<button type="button" class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log Out</button>
						  </a>
					</div>
				</a>
				<span style="margin-top: 5px; margin-left: 10px; height: 40px; width: 40px; font-family: 'Josefin Sans'; font-size: 25px; text-align: center; background-color: #102542; border-radius: 50%; color: #fff;">{{ user.username.0 }}</span>
			{% else %}
				<a href="/#log-in">
					<div class="social-icons-header">
						<button class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log In</button>
					</div>
				</a>
			{% endif %}
		  </ul>
		</div>
	  </nav>

        {% block desc %}
		<div class="container fh5co-hero-inner">
			<h1 class="animated fadeIn wow" data-wow-delay="0.4s" id="h1-home">STACES</h1>
			<p class="animated fadeIn wow" data-wow-delay="0.67s" id="p-header">Your bestfriend in quarantine!</p>
        </div>
        {% endblock %}

		
    </div> <!-- first section wrapper -->

    {% block content %}
    {% endblock %}
    
    <!-- ==========================================================================================================
                                               FOOTER
    ========================================================================================================== -->

	<footer class="footer-outer">
		<div class="container footer-inner">

			<div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
				<div>
					<nav class="footer-nav">
						<ul>
							<h1 id="h1-footer"> STACES </h1>
							<p>By using our website, we hope that we helped you. Stay safe, stay healthy, and stay clean!<br>
							If there is any problem, please let we know.</p>
						</ul>
						<ul>
							<div class="social-icons-footer">
								<a target="_blank" href="https://instagram.com/stacesapp/"><i class="fab fa-instagram"></i></a>
								<a target="_blank" href="mailto: stacesapp@gmail.com"><i class="fa fa-envelope"></i></i></a>
							</div>
						</ul>
						<ul>
							<p class="copyright" id="p-copyright">Copyright © 2020. All Rights Reserved</p>
						</ul>
					</nav>
				</div>
			</div>
			<span></span>
			<p class="copyright"></p>
		</div>
	</footer>

</div> <!-- main page wrapper -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="{% static 'js/todo.js' %}"></script>
</body>
</html>

todo/templates/main/todo.html
{% extends 'main/navfoot-todo.html' %}
{% load static %}

{% block meta %}
<title>TO DO - Main Page</title>
{% endblock meta %}

{% block desc %}
<div class="d-sm-flex flex-sm-row flex-row animated fadeIn wow container todo-desc">
  <div class="d-flex flex-column p-3">
    <div class="todo-section-title">TO DO</div>
    <div class="todo-section-desc" style="font-family: Josefin Sans; font-size: 17px;">
      You can easily manage your tasks here. 
      These tasks will be divided into two categories, such as group tasks and personal tasks. 
      Not only that, the tasks will be sorted based on the closest deadline, both day and time. 
      For previous tasks that you have done, there will be a delete button or simply a mark for the completed tasks.
    </div>
  </div>
  <div class="p-2">
    <img class="todo-logo" src="{% static 'img/todo-logo.png' %}" alt="todo-logo">
  </div>
</div>
{% endblock %}

{% block content %}
<div class="animated fadeIn wow container content">

  {% if user.is_authenticated %}

  <div class="d-flex flex-column">
    <div class="d-flex flex-row justify-content-between">
      <div class="btn-group dropright">
        <button type="button" class="btn task-categories dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Task Category 
        </button>
     
        <div class="dropdown-menu">
          <a class="dropdown-item task-category" id="personal-tasks">Personal Tasks</a>
          <a class="dropdown-item task-category" id="group-tasks">Group Tasks</a>
        </div>
      
      </div>

  </div>

    <div class="d-flex flex-row justify-content-between">
      {% block task-title %}
      <h1 class="task-title">Tasks for You!</h1>

      <div class="button-link">
        <a href="{% url 'todo:addTask' %}">
          <div class="add-button">+</div>
        </a>
      </div>
      {% endblock %}
    </div>
  </div>
  
  {% if allTask.count != 0 %}
  <div id="list-of-personal-task">
  {% for task in allTask %}
  <div class="d-flex flex-column task-detail">
    <div class="d-flex flex-row justify-content-between">
      <div class="task-name">{{task.title}}</div>
      <div class="task-datetime">{{task.time}}</div>
    </div>
    <div class="d-flex flex-row justify-content-between">
      <div class="task-description">{{task.description}}</div>
      {% csrf_token %}
      <div class="trash-btn" data-id="{{task.id}}"><i class="fa fa-trash"></i></div>
    </div>
    <div class="task-datetime">{{task.date}}</div>
  </div>
  {% endfor %}
  </div>
  
  {% endif %}

  {% else %}
  <div class="warning">
    <div class="warning-title">
      Authentication Required
    </div>
    <div class="warning-description">
      Please <a href="/register/" class="to-register">sign up</a> or <a href="/#log-in" class="to-register">log in</a> first to access this feature
    </div>
  </div>

  {% endif %}


</div>
{% endblock content %}